[package]
name = "decision_tree_builder_impl"
version = "0.0.2"
authors = ["Jakub Zawadzki <kuba.zaw@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
syn = "1.0.107"
quote = "1.0.23"
proc-macro2 = "1.0.49"

[dev-dependencies]
prettyplease = "0.1.23"
